### ISSUE TITLE
Is this project halted?

### ISSUE THREAD

**Issue by mjyc** [Widdershin/bonsai-editor#1]
Hi @Widdershin , I've been looking for cycle.js GUI-based stream editor and stumbled on this. It seems the project has been inactive for a while and was wondering why. I saw one alternative tool, [bonsai-rx](https://bonsai-rx.org/), but it's windows only software and that makes it very difficult for me. Plus, I'm already a cycle.js user so this seems like a perfect choice for me.

Do you plan to resume developing or did you find any other reasonable alternative?

**Comment by Widdershin** [comment]
Hi @mjyc, thanks for your interest.

I'm not currently planning to resume developing bonsai-editor.

After some conversations with @staltz at CycleConf 2017, he convinced me that it was important for any visual editor to support a hybrid visual and textual interface, and to be able to import existing textual codebases.

This also coincided with some other problems I was working through, and as a result I decided that rather than attempting to fit a system like this on top of JavaScript/TypeScript, it would make more sense to design a new language from the ground up that would support different types of syntax including a visual format.

So in that sense, work on bonsai-editor is continuing through the programming language I am developing, [Forest](http://github.com/forest-lang/forest-compiler). I haven't yet started work on a visual editor for Forest, but the intent is to build something like bonsai for Forest, and achieve the goal of having a visual editor for Cycle.js-style apps.

Let me know if you have any other questions 😸

**Comment by mjyc** [comment]
Thanks for the quick reply, seems like FAQ section of the Forest repo contains answers to my question!
